### ISSUE TITLE
关于使用Hexo模板静态博客自动更新

### ISSUE THREAD

**Issue by azouever** [AmosWang0626/auto#1]
偶然看到你的博客，看到关于自动更新的问题，看到了你的实现做法；但是我发现不能评论，于是我就来这里了，就想给你分享下我的做法，哈哈。
我的是直接在我的服务器上面搭建了git仓库，同时github上 也会push，就是同时push到两个仓库里面；然后在自己服务器上面的git上面配置好hook，去执行hexo相关的脚本；博客直接更新；这样我每次直接修改只要push一下就好了。

因为其实就一个文件夹，没有用相关的git可视化工具，所以每次都会去终端下面push；觉着比较麻烦；我又写了个脚本，通过toggle alfred 配置快捷键直接可以打开终端然后进行push；

发现每次打开终端push的时候，要执行一些内容，会有输出，我还得等一小会，而且终端窗口还需要我手动关闭「觉得特麻烦，虽然只是一个小动作」，于是我就又加了一行osascript 的脚本，将当前窗口最小化

**最后：我通过快捷键 输入commit msg 然后回车「我的动作已经结束，后面的都是自动的」，终端打开，然后开始push，同时窗口最小化「不用管它」，push完事了窗口会自动关闭；**

就是你起了一个服务监听，而我直接搞了两个仓库 ，觉着内容不多。
就是想分享一下静态博客自动更新的这个过程，觉得挺有意思。

**Comment by AmosWang0626** [comment]
> 偶然看到你的博客，看到关于自动更新的问题，看到了你的实现做法；但是我发现不能评论，于是我就来这里了，就想给你分享下我的做法，哈哈。
> 我的是直接在我的服务器上面搭建了git仓库，同时github上 也会push，就是同时push到两个仓库里面；然后在自己服务器上面的git上面配置好hook，去执行hexo相关的脚本；博客直接更新；这样我每次直接修改只要push一下就好了。
> 
> 因为其实就一个文件夹，没有用相关的git可视化工具，所以每次都会去终端下面push；觉着比较麻烦；我又写了个脚本，通过toggle alfred 配置快捷键直接可以打开终端然后进行push；
> 
> 发现每次打开终端push的时候，要执行一些内容，会有输出，我还得等一小会，而且终端窗口还需要我手动关闭「觉得特麻烦，虽然只是一个小动作」，于是我就又加了一行osascript 的脚本，将当前窗口最小化
> 
> **最后：我通过快捷键 输入commit msg 然后回车「我的动作已经结束，后面的都是自动的」，终端打开，然后开始push，同时窗口最小化「不用管它」，push完事了窗口会自动关闭；**
> 
> 就是你起了一个服务监听，而我直接搞了两个仓库 ，觉着内容不多。
> 就是想分享一下静态博客自动更新的这个过程，觉得挺有意思。

嗯呐，服务器上搭个仓库，然后执行自定义的hook，也挺方便的，还省去了暴露公网接口。Get 了 Mac 脚本相关工具，感谢分享哟~
